---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "Install Nodejs"
  become: true
  yum:
    name: ['nodejs']
    state: present
    update_cache: yes

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: true
    production: true
    state: present

#Adapted from the classroom solution
- name: "create ~/web"
  ansible.builtin.file:
    path: ~/web
    state: directory
    mode: '0755'

- name: "Install index.js"
  copy:
    src: index.js
    dest: ~/web/index.js
    backup: yes 

#Experiment the clasroom solution
- name: "start server"
  shell: pm2 start ~/web/index.js -f